### ISSUE TITLE
Plugin is looking for qunit.js file along with my tests.html file

### ISSUE THREAD

**Issue by svankamamidi** [gruntjs/grunt-contrib-qunit#132] opened 2016-07-26 13:23 UTC
Hi,

I tried loading qunit js from both tests.html and through require, but irrespective of how I load qunit, when I run grunt task to run qunit tests it is failing tests with timeout and in the error it states quint.js is not found in the same folder where my tests.html is present. I am able to overcome this issue by simply copying the qunit.js file. I don't want to keep qunit.js in this additional location, can you please share your thoughts why it is looking for qunit.js at this specific location.

Thanks
Sudhakar

**Comment by Arkni** [comment] 2016-07-26 14:12
Can you show us your code ?
Do you have a path for the `qunit` module defined ?
```js
require.config({
  paths: {
    // ...
    qunit: "path/to/qunit"
  }
});
```

**Comment by svankamamidi** [comment] 2016-07-27 05:19
Yes, in my testMain.js I have qunit module defined
'qunit': LIB + 'utils/helpers/qunit/qunit'

My Gruntfile.js entry as shown below:
qunit: {
            options: {
                timeout: 10000
            },
            all: ['app/test/tests.html']
}

Still failing if I don't have qunit.js in folder app/test/

Thanks
Sudhakar

**Comment by Arkni** [comment] 2016-07-27 12:53
Still not clear to me what causes the problem. Can you provide more code (tests.html, testMain.js ...), you can create a repository here in GitHub so I can check it and test it.

**Comment by svankamamidi** [comment] 2016-08-04 09:20
Here is my testMain.js trimmed contents:
`    LIB = '../app/f/';
    requirejs.config({
        baseUrl: "../",        
        paths: {
			//Paths.....
            'qunit': LIB + 'qunit/qunit'
        },      
        shim: {
            'jquery': {
                exports: ['jQuery', '$']
            },
            'mockjax': {
                deps: ['jquery']
            }
        },        
        config: {
            ojL10n: {
                merge: {
                }
            }
        }
    });
    var testModules = ['jquery',
        "modules/myTests.js",

    ];
    require(testModules, function ($, QUnit) {
        QUnit.config.autostart = false;
        QUnit.load();
        QUnit.start();
    });`

Here is my trimmed down tests.html
`<!DOCTYPE html>
<html lang="en-us" >
    <head>             
        <link rel="stylesheet" href="../../app/f/qunit/qunit.css">              
        <script src="../../app/f/require.js" data-main="testMain.js"></script>                       
    </head>
    <body>        
        <div id="qunit"></div>
        <div id="qunit-fixture"></div>        
    </body>
</html>
`

Thanks
Sudhakar

**Comment by Arkni** [comment] 2016-08-04 19:16
The problem caused by the fact that `PhantomJS` inject the bridge file before `RequireJS` can define the path to `QUnit` (loading the file `testMain.js`) which result in `RequireJS` throwing the error: `Error: Script error for "qunit"`, hence the timeout.

To solve the problem, you can follow the same approach used in `QUnit` tests:
* html: https://github.com/jquery/qunit/blob/master/test/amd.html
* js: https://github.com/jquery/qunit/blob/master/test/amd.js

For a similar solution, see http://stackoverflow.com/a/29890894/3904791

I know this is not the optimal solution, but there is an open discussion in #127 about making the bridge file a named module (e.g: `phantomjs-bridge`). With that, you can do the following:
```html
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>QUnit AMD Test Suite</title>
    <link rel="stylesheet" href="../node_modules/qunitjs/qunit/qunit.css">
    <script data-main="main" src="../node_modules/requirejs/require.js"></script>
</head>
<body>
    <div id="qunit"></div>
</body>
</html>
```

```js
require.config({
    paths: {
        // ...
        qunit: "../node_modules/qunitjs/qunit/qunit"
    }
});

// Load the bridge
require(["phantomjs-bridge"]);

// And then run the tests
require(["qunit", "./tests"], function(QUnit, tests) {
    tests();
    QUnit.start();
});

// Or
require(["qunit", "./tests", "phantomjs-bridge"], function(QUnit, tests) {
    tests();
    QUnit.start();
});
```

**Comment by Arkni** [comment] 2016-08-04 19:17
Will close this issue for now.
Feel free to ask if you have followup question.

**Closed by Arkni** 2016-08-04 19:17 UTC
