### ISSUE TITLE
global failure - Can't find variable: seajs

### ISSUE THREAD

**Issue by tuijs** [gruntjs/grunt-contrib-qunit#64] opened 2014-04-09 08:37 UTC
hi all, I need your help!

>grunt qunit
Running "qunit:all" (qunit) task
Testing tests/test.html F
>> global failure
>> Message: ReferenceError: Can't find variable: seajs
>> file:///E:/workspace/webstorm/tui.pek/tuijs/tests/test.html:20

Warning: 1/1 assertions failed (20ms) Use --force to continue.

Aborted due to warnings.

test.html like this:
<html>
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=UTF-8">
    <title>Tuijs Unit Test</title>
    <link href="qunit/qunit-1.14.0.css" rel="stylesheet"/>
<body>
    
    <script src="qunit/qunit-1.14.0.js"></script>
    <script src="../dist/sea-2.1.1.js"></script>
    <script src="../dist/tui.config.js"></script>
    <script>

        (function(){
            seajs.use(['tuiInit'], function(){
                $.extend(seajs.data.alias, {testInit: '../tests/test.Init.js'});
            });
            seajs.use(['testInit'], function(){});
        })();

    </script>

</body>
</html>

**Comment by theUtherSide** [comment] 2015-02-19 00:46
I'm having a similar issue running using jQuery.  When I view my test page in the browser, I get no errors, jQuery loads fine and is used in tested code and tests.

When running through Grunt/PhantomJS, i get an error saying jQuery can't be found.

**Comment by Arkni** [comment] 2016-02-19 01:34
Can't reproduce using latest releases.

Closing for now, will reopen if the issue persist.

**Closed by Arkni** 2016-02-19 01:34 UTC
