### ISSUE TITLE
Seeing "Error: ReferenceError: QUnit is not defined"

### ISSUE THREAD

**Issue by mattyrob** [gruntjs/grunt-contrib-qunit#202] opened 2023-06-20 16:06 UTC
ClassicPress, which is an open source fork of WordPress uses this npm dependency to facilitate QUnit automated testing.

The project currently uses version 6.0.0. Renovate has made the project aware of updated versions, however we are seeing an issue in command line testing on updating to version 6.1.0 and above.

https://github.com/ClassicPress/ClassicPress-v2/actions/runs/5236023222/jobs/9453262414

<img width="848" alt="Screenshot 2023-06-20 at 17 01 11" src="https://github.com/gruntjs/grunt-contrib-qunit/assets/1280733/2527ffd0-9917-4b48-b428-d229eae7b8f2">

The QUnit tests work perfectly in a browser window and I have tracked the issue back to the Chrome bridge, line [14](https://github.com/gruntjs/grunt-contrib-qunit/blob/240436f17e0a67daf520e745c54a48195aaa7e1a/chrome/bridge.js#L14), where it seems that on occasion `QUnit` is not yet available.

This same issue exists in [WordPress](https://core.trac.wordpress.org/ticket/56250).

The tests still seems to work and pass.

Any advice you could give would be appreciated.

**Comment by Krinkle** [comment] 2023-06-20 20:05
Something interesting is definitely going on here!

I'll take for granted that the `<anonymous>` in your trace refers to [grunt-contrib-qunit's chrome bridge.js](https://github.com/gruntjs/grunt-contrib-qunit/blob/240436f17e0a67daf520e745c54a48195aaa7e1a/chrome/bridge.js#L14).

Fistly, it's interesting that the bridge.js line is the very first executable reference to `QUnit`. If that really failed at the time where it matters (when our code injects bridge.js into the browser), then no single test could run, and we'd have no dot-reporting `......` results. Yet, tests do run.

Secondly, the start of the stack trace (bottom frame) is interesting. It points to one of your TinyMCE tests, inside the WordPress/ClassicPress test suite at https://github.com/ClassicPress/ClassicPress-v2/blob/develop/tests/qunit/wp-includes/js/tinymce/tinymce-obsolete.js#L258. This test is halfway a QUnit module, and thus further indicates that QUnit is working and the bridge was injected and executed successfully.

It appears that these TinyMCE tests are creating an iframe, and then re-running some (but not all?) JavaScript code from the parent page a second time inside of that iframe. It appears to not import QUnit there, which is fine, except it decides to re-eval the bridge.js script for some reason. I'm not sure why or how it is doing that, but this seems difficult to support or protect against from our end.

The reason that these uncaught errors don't produce in CI failures, is that we only only know about the web page where the test suite runs. The anonymous iframes created by individual tests are not in our control and we don't have a reference to their local Window object or their Window.onerror handler. And besides, if the project you work on created iframes intentionally, you may very well have tests that expect certain kinds of errors on purpose, so we wouldn't want to consider those uncaught errors as failures anyway. In this case the word "QUnit" there obviously looks scary and important from a CI perspective. I suspect, though, that even if we changed this file somehow to not reference QUnit, you'd find a different error for a different undefined class of some kind. I think the reason `QUnit` is reported here is that TinyMCE is discovering our injected bridge file as the first script it copies over so it is the first to fail and expose this behaviour.

Do you know more about TinyMCE and how and why its tests might be copying over JavaScript tags to its iframe fixtues?

**Comment by mattyrob** [comment] 2023-06-21 07:42
@Krinkle - thank you for the rapid and insightful response. I have tracked back through the `tinymce.min.js` and `tinymce-obsolete.js` files and in each case the referenced code is creating an iframe.

In the latter case the `tinymce-obsolete.js` file is testing directly to make sure that any `iframe` element that is created in the TinyMCE editor is conforming to HTML5 standards in terms of the attributes.

So do you think this is because the bridge is attempting to load QUnit in those frames?

**Comment by carhartl** [comment] 2023-06-21 11:42
We're seeing the same here: https://github.com/gruntjs/grunt-contrib-qunit/issues/202

**Comment by carhartl** [comment] 2023-06-21 11:44
..we are also creating iframes as part of our testing.

**Comment by carhartl** [comment] 2023-06-21 12:28
Ah.. in our particular case I was able to work around the noisy errors like this:

```
options: {
  inject: [
    'fix-qunit.js',
    'node_modules/grunt-contrib-qunit/chrome/bridge.js'
  ]
}
```

```js
// fix-qunit.js
if (window.parent) window.QUnit = window.parent.window.QUnit
```

**Comment by Krinkle** [comment] 2023-06-22 21:39
> So do you think this is because the bridge is attempting to load QUnit in those frames?

Yes, or more exactly, the bug is that the bridge is injected into an iframe at all.

Note that the bridge does not (try to) load QUnit. Your HTML test page loads QUnit normally. The bridge merely plugs into the existing QUnit object on any web page, and sends test results back to the Node.js/Grunt process.

I was looking for how and why TinyMCE (or its test suite) is copying scripts from the test.html page to its iframes, and found nothing. Your question led me to take a closer look at what the bridge.js file is doing. I do not consider as a likely suspect because the problem we see _ends_ at the first line of the bridge.js file, so something goes wrong before that already.

There's no way in ordinary HTML/JavaScript for a script to run inside an iframe unless the code creating the iframe is doing that. The key phrase here is "ordinary HTML/JavaScript".

We run the tests in Puppeteer on Headless Chromium, which exposes a few "extra"-ordinary abilities to inject scripts. This of course is how bridge.js is injected into the test.html page.

What I didn't realize, is that Puppeteer applies this to at the low-level concept of any Document context, not just browser tabs and top-level navigations:

```js
page.evaluateOnNewDocument( "… contents of bridge.js …" );
page.goto( url );
```

https://pptr.dev/api/puppeteer.page.evaluateonnewdocument/

This has apparently bitten other people in the past (ref https://github.com/puppeteer/puppeteer/issues/2738).

Anyway, now that the root cause is found, I will make sure this gets fixed in grunt-contrib-qunit. The fix is relatively simple. I believe the fix is backwards-compatible with our workaround, but after your next upgrade, you can remove the workaround as well.

**Comment by mattyrob** [comment] 2023-07-01 16:06
Potential fix, one that I've tested locally and that works for me is as follows:

```
* global QUnit:true */
(function (factory) {
  if (window.self !== window.top) {
    return;
  }
  if (typeof define === 'function' && define.amd) {
    require(['qunit'], factory);
  } else {
    factory(QUnit);
  }
}
```

A check to ensure that the Bridge.js fine is only injected into the top parent window.
Is that a valid fix or might it cause issues elsewhere?

**Comment by Krinkle** [comment] 2023-07-01 20:31
@mattyrob Yep, that should do indeed. Would you mind opening a PR?

**Closed** 2023-07-02 19:01 UTC
Labels: bug
