### ISSUE TITLE
No errors are given for violations of "use strict" 

### ISSUE THREAD

**Issue by ZodsPlan** [gruntjs/grunt-contrib-qunit#83] opened 2014-09-28 20:09 UTC
I have javascript code being tested by grunt-contrib-qunit, but I realize that the code is allowed to violate "use strict" settings that I have in my javascript code; although, if I run the qunit tests in the browser, then errors are thrown when there are violations of "use strict".  grunt-contrib-qunit seems to ignore "use strict";.

**Comment by Hirse** [comment] 2016-01-25 15:21
Have you tried to run it with the `noGlobals` flag?
https://github.com/gruntjs/grunt-contrib-qunit#noglobals

**Comment by Arkni** [comment] 2016-03-09 00:33
Can't reproduce using latest versions.

Closing for now, will reopen if the issue persist.

**Closed by Arkni** 2016-03-09 00:33 UTC
