### ISSUE TITLE
QUnit doesn't exit phantomjs

### ISSUE THREAD

**Issue by sateffen** [gruntjs/grunt-contrib-qunit#75] opened 2014-07-09 12:50 UTC
I'm using this plugin for my grunt as testrunner for some tests, but after some time my computer has no memory left. I checked why, and saw far over 100 phantomjs processes running. So, I've gone further and realized, that for every url in the urls: [] array this runner starts a new phantomjs, and the old process is left alone.
Usually I would expect, that this runner starts one phantomjs, let this call every url and exits the phantomjs then.

My setup:
Windows 7 professional 64bit
grunt-cli: v0.1.13
grunt: v0.4.5
grunt-contrib-qunit: 0.5.1
If important: I'm using grunt-qunit-junit version 0.1.0

Grunt configuration:
	qunit: {
		all: {
			options: {
				'--load-images': false,
				urls: [<filled by a function with a lot of links to htmlfiles>]
			}
		}
	},

This is pretty much eating up all my memory (I was wondering why my 8gig of ram were full)

If you need something else to know, just ask

**Comment by Arkni** [comment] 2016-02-19 00:10
I can't reproduce with the latest version.
Closing for now. Will reopen when the issue is reproducible.

**Closed by Arkni** 2016-02-19 00:10 UTC
