### ISSUE TITLE
npm test not working.

### ISSUE THREAD

**Issue by dtracers** [gruntjs/grunt-contrib-qunit#100] opened 2015-06-01 04:07 UTC
Hi.  I forked the repository then tried to run  npm test but it is not working.

It is saying:
```
Running "qunit:all_tests" (qunit) task
Testing test/qunit1.html Warning: Cannot read property 'connected' of undefined Use --force to continue.
```

I am trying to add Webdriverio so that we can use chrome instead of just phantomjs but I can not even get the version in master working.

Thanks in advance!

**Comment by shinehuaking** [comment] 2015-09-21 09:03
add one, I have met the same problem

**Comment by sculove** [comment] 2015-10-05 10:03
+1

**Comment by Arkni** [comment] 2016-02-18 18:14
@dtracers 
Do you still encountering this issue with the latest version ?

**Comment by dtracers** [comment] 2016-02-18 19:28
I actually found a different repo so I am not sure if this is solved or
when I can check if it is still a problem
On Feb 18, 2016 12:14 PM, "Brahim Arkni" <notifications@github.com> wrote:

@dtracers <https://github.com/dtracers>
Do you still encountering this issue with the latest version ?

—
Reply to this email directly or view it on GitHub
<https://github.com/gruntjs/grunt-contrib-qunit/issues/100#issuecomment-185842618>
.

**Comment by Arkni** [comment] 2016-02-18 19:43
Closing this for now. Will open when the issue is reproducible using the latest version.

**Closed by Arkni** 2016-02-18 19:43 UTC
